const plant = [
    { 
        Name: "Ashwagandha (Withania somnifera)",
        Image: "https://upload.wikimedia.org/wikipedia/commons/a/ad/WithaniaFruit.jpg",
        Info: "The plant, particularly its root powder, has been used for centuries in traditional Indian medicine.Ashwagandha supplements, typically containing    root or leaf powder or extracts, are commonly sold. Its use in herbal medicine and dietary supplements notwithstanding.",
        Tags: ["ashwagandha", "Withania somnifera"],
        Disease: ["thyroid imbalances", "adrenal fatigue and chronic fatigue syndrome", "Stress, anxiety, depression"],
        HowItworks: "Ashwagandha’s adaptogenic properties help balance cortisol levels, reduce stress, improve sleep quality, and support energy levels.",
        SideEffects: ["stomach upset", "diarrhea", "nausea", "drowsiness"],
        Exceptions: ["Pregnant women", "People with thyroid disorder", "individuals with autoimmune diseases"],
        Availability: "India, North Africa, and the Middle East",
    },
    {
        Name: "Tulsi(Ocimum sanctum)",
        Image: "https://upload.wikimedia.org/wikipedia/commons/0/01/Tulsi_or_Tulasi_Holy_basil.jpg",
        Info: "In Hinduism, tulsi is worshipped as a goddess. Tulsi is a small, bushy plant with slightly hairy stems, fragrant leaves, and purple flowers. It is native to the Indian subcontinent but is now grown worldwide in tropical regions.",
        Tags: ["Ocimum sanctum", "Tulsi", "Holy Basil", ],
        Diseases: ["Immune Booster", "Respiratory Health", "Stress Relief and Mental Health", "Heart Health", "Anti-Diabetic Effects"],
        HowItworks: "Tulsi acts as an immune modulator, expectorant, and anti-inflammatory, making it effective against respiratory issues and boosting immunity. It also has adaptogenic properties that help manage stress.",
        SideEffects: ["Long-term use may lower fertility in men", ],
        Exceptions: ["pregnant or breastfeeding women", "diabetes patient", "Heart patient"],
        Availability: "utheast Asia, Africa, and some regions in the Americas",
    },
    {
        Name: "Neem(Azadirachta indica)",
        Image: "https://upload.wikimedia.org/wikipedia/commons/2/20/Neem_%28Azadirachta_indica%29_in_Hyderabad_W_IMG_6976.jpg",
        Info: "It is a fast-growing tree that can reach a height of 15 To 20 metres (49 to 66 ft), and rarely 35 to 40 m (115 to 131 ft). It is evergreen, shedding many of its leaves during the dry winter months. The branches are wide and spreading. The fairly dense crown is roundish and may reach a diameter of 20 to 25 m (66 to 82 ft).",
        Tags: ["Neem", "Azadirachta indica"],
        Diseases: ["Skin conditions (acne, eczema, psoriasis)", "diabetes", "infections", "gum diseases", "digestive issues"],
        HowItworks: "Neem has antibacterial, antifungal, and antiviral properties, which make it effective for skin infections and oral health. It also helps regulate blood sugar levels and has purifying effects on the blood.",
        SideEffects: ["nausea", "vomiting", "diarrhea", "Long-term use can harm the liver and kidneys"],
        Exceptions: ["Pregnancy Women", "young children"],
        Availability: "Indian subcontinent, particularly in dry and semi-arid regions",
    },
    {
        Name: "Amla (Emblica officinalis)",
        Image: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Phyllanthus_officinalis.jpg",
        Info: "he tree is small to medium in size, reaching 1 to 8 metres (3.5 to 26 feet) in height. The bark is mottled. The branchlets are finely pubescent (not glabrous), 10 to 20 centimetres (4 to 8 inches) long, usually deciduous. The leaves are simple, subsessile and closely set along branchlets, light green, resembling pinnate leaves. The flowers are greenish to yellow. The fruit is nearly spherical, light greenish to yellow, quite smooth and hard on appearance, with six vertical stripes or furrows. The fruit is up to 26 millimetres (1 in) in diameter, and, while the fruit of wild plants weigh approximately 5.5 grams (0.2 ounces), cultivated fruits average 28.4 g (1 oz) to 56 g (2 oz).",
        Tags: ["Amla", "Emblica officinalis"],
        Diseases: ["Common cold, flu", "immune deficiency", "high cholesterol", "skin aging", "digestive issues"],
        HowItworks: "Amla’s high Vitamin C content boosts immunity, supports healthy digestion, and aids in cholesterol management. Its antioxidant properties make it valuable for skin health and slowing down aging.",
        SideEffects: ["Generally safe in moderate amounts, but high doses may cause acid reflux or upset stomach"],
        Exceptions: ["hypoglycemia"],
        Availability: "Primarily found in India and Southeast Asia",
    },
    {
        Name: "Turmeric (Curcuma longa)",
        Image: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Curcuma_longa_roots.jpg",
        Info: "The leaves are alternate and arranged in two rows. They are divided into leaf sheath, petiole, and leaf blade. From the leaf sheaths, a false stem is formed. The petiole is 50 to 115 cm (20 to 45 in) long. The simple leaf blades are usually 76 to 115 cm (30 to 45 in) long and rarely up to 230 cm (7 ft 7 in). They have a width of 38 to 45 cm (15 to 17 in) and are oblong to elliptical, narrowing at the tip.",
        Tags: ["Turmeric", "Curcuma longa"],
        Diseases: ["Arthritis, joint pain", "inflammation", "digestive disorders", "skin diseases", "liver conditions", "respiratory problems"],
        HowItworks: "Turmeric’s active compound, curcumin, is a strong anti-inflammatory and antioxidant that helps relieve joint pain, promotes liver health, and aids in digestive issues. It is also known to boost immune response and provide natural support against infections.",
        SideEffects: ["digestive issues such as acid reflux, diarrhea, or nausea", "High doses may increase the risk of bleeding"],
        Exceptions: ["individuals with gallbladder issues", "individuals on blood-thinning medications"],
        Availability: "India and Southeast Asia",
    },
    {
        Name: "Shatavari (Asparagus racemosus)",
        Image: "https://upload.wikimedia.org/wikipedia/commons/3/34/Asparagus_racemosus.JPG",
        Info: 'It grows 1to 2 m (3 ft 3 in to 6 ft 7 in) tall and prefers to take root in gravelly, rocky soils high up in piedmont plains, at 1,300 to 1,400 m (4,300 to 4,600 ft) elevation. It was botanically described in 1799. Because of its multiple uses, the demand for Asparagus racemosus is constantly on the rise. Due to destructive harvesting, combined with habitat destruction, and deforestation, the plant is now considered "endangered" in its natural habitat.',
        Tags: ["Shatavari", "Asparagus racemosus"],
        Diseases: ["Hormonal imbalances", "PMS", "menopausal symptoms", "infertility", "immune deficiency","digestive disorders"],
        HowItworks: "Shatavari is known for balancing female hormones, promoting reproductive health, and improving immunity. Its soothing effects are beneficial for gastrointestinal issues, including acid reflux and ulcers.",
        SideEffects: ["may cause mild gastrointestinal discomfort, including bloating or gas", "allergic reactions in those sensitive to asparagus", "affect hormone levels"],
        Exceptions: [],
        Availability: "Indian subcontinent, particularly in tropical and subtropical areas.",
    },{
        Name: "Brahmi (Bacopa monnieri)",
        Image: "https://upload.wikimedia.org/wikipedia/commons/5/56/Starr_010818-0007_Bacopa_monnieri.jpg",
        Info: "It is known by the common names water hyssop, waterhyssop, brahmi, thyme-leafed gratiola, herb of grace, and Indian pennywort. Bacopa monnieri is used in Ayurveda. In 2019, the US Food and Drug Administration (FDA) warned manufacturers of dietary supplement products containing Bacopa monnieri against making illegal and unproven claims that the herb can treat various diseases",
        Tags: ["Brahmi", "Bacopa monnieri", "Water"],
        Diseases: ["Memory loss", "cognitive decline", "ADHD", "anxiety", "depression", "insomnia"],
        HowItworks: "Brahmi is a nootropic (cognitive enhancer) and helps improve memory, focus, and mental clarity. It is also known to reduce anxiety and aid sleep, making it useful for mental health support.",
        SideEffects: ["nausea", "dry mouth", "fatigue", "digestive discomfort"],
        Exceptions: ["pregnant woman", "individuals with low blood pressure"],
        Availability: "Wetlands of India, Australia, Europe, Africa, and Asia.",
    },{
        Name: "Triphala",
        Image: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Phyllanthus_officinalis.jpg",
        Info: 'Triphala ("three fruits") is an Ayurvedic herbal rasayana formula consisting of 1:2:3 parts of three herbs i.e Haritaki:Bibhitaki:Amlaki.. It contains vitamin C',
        Tags: ["Triphala"],
        Diseases: ["Constipation", "digestive disorders", "obesity", "skin diseases", "immune deficiencies"],
        HowItworks: "Triphala supports digestive health, acts as a mild laxative, and aids in detoxification. It is also an immune booster and promotes general well-being by balancing the body’s doshas (Vata, Pitta, and Kapha).",
        SideEffects: ["diarrhea", "cramping", "gastrointestinal discomfort"],
        Exceptions: [],
        Availability: "India, Southern Asia,",
    },{
        Name: "Guduchi (Tinospora cordifolia)",
        Image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Tinospora_cordifolia.jpg/800px-Tinospora_cordifolia.jpg",
        Info: "Tinospora cordifolia (common names heart-leaved moonseed, amrita, guduchi (in Sanskrit), gurbel or giloy, among others) is a herbaceous vine of the family Menispermaceae indigenous to tropical regions of the Indian subcontinent. It has been used in Ayurveda to treat various disorders.",
        Tags: ["Guduchi", "Tinospora cordifolia"],
        Diseases: ["Fever, respiratory issues, diabetes, arthritis, liver diseases, and immune deficiencies"],
        HowItworks: "Guduchi is an immune modulator that helps fight infections, reduce inflammation, and manage fever. It also supports liver health, is helpful in managing blood sugar levels, and can alleviate symptoms of arthritis",
        SideEffects: ["Mild digestive discomfort", "lower blood sugar levels excessively"],
        Exceptions: ["autoimmune diseases", "Sugar Patients"],
        Availability: "Indian subcontinent, found primarily in forests and tropical regions.",
    },
    {
        Name: "Moringa (Moringa oleifera)",
        Image: "https://upload.wikimedia.org/wikipedia/commons/2/2e/DrumstickFlower.jpg",
        Info: "M. oleifera is a fast-growing, deciduous tree that can reach a height of 10 to 12 m (33 to 39 ft) and trunk diameter of 46 cm (18 in). The bark has a whitish-gray color and is surrounded by thick cork. Young shoots have purplish or greenish-white, hairy bark. The tree has an open crown of drooping, fragile branches, and the leaves build up a feathery foliage of tripinnate leaves.",
        Tags: ["Moringa", "Moringa oleifera"],
        Diseases: ["Malnutrition", "anemia", "high blood pressure", "inflammation", "digestive issues", "immune deficiency"],
        HowItworks: "Moringa is highly nutritious, supporting overall health and boosting energy levels. Its anti-inflammatory properties are beneficial for managing high blood pressure, digestive issues, and supporting immunity",
        SideEffects: ["digestive issues like nausea, diarrhea, or stomach upset", "liver issues", "kidney issues",],
        Exceptions: ["thyroid", "Pregnanct womens"],
        Availability: "Indian subcontinent and parts of Africa",
    },
    // {
    //     Name: "",
    //     Image: "",
    //     Info: "",
    //     Tags: [],
    //     Diseases: [],
    //     HowItworks: "",
    //     SideEffects: [],
    //     Exceptions: [],
    //     Availability: "",
    // },
]

export default plant;